version: "3.8"

services:
  proxy:
    image: nginx:latest
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server
    ports:
      - target: 3000
        published: 3000
        mode: host

  server:
    # image: niskii/coderforum_api:latest
    build:
      context: .
    ports:
      - target: 80
